<?php

namespace ContainerXTjQmX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MsqDT9oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.msqDT9o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.msqDT9o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AjouterController::ajouter' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::change' => ['privates', '.service_locator.no630kw', 'get_ServiceLocator_No630kwService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\WishController::deleteMyWish' => ['privates', '.service_locator.67PgdOa', 'get_ServiceLocator_67PgdOaService', true],
            'App\\Controller\\WishController::modifyMyWish' => ['privates', '.service_locator.67PgdOa', 'get_ServiceLocator_67PgdOaService', true],
            'App\\Controller\\WishController::wish' => ['privates', '.service_locator.vAoeUqn', 'get_ServiceLocator_VAoeUqnService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AjouterController:ajouter' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:change' => ['privates', '.service_locator.no630kw', 'get_ServiceLocator_No630kwService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\WishController:deleteMyWish' => ['privates', '.service_locator.67PgdOa', 'get_ServiceLocator_67PgdOaService', true],
            'App\\Controller\\WishController:modifyMyWish' => ['privates', '.service_locator.67PgdOa', 'get_ServiceLocator_67PgdOaService', true],
            'App\\Controller\\WishController:wish' => ['privates', '.service_locator.vAoeUqn', 'get_ServiceLocator_VAoeUqnService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AjouterController::ajouter' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::change' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\WishController::deleteMyWish' => '?',
            'App\\Controller\\WishController::modifyMyWish' => '?',
            'App\\Controller\\WishController::wish' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AjouterController:ajouter' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:change' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\WishController:deleteMyWish' => '?',
            'App\\Controller\\WishController:modifyMyWish' => '?',
            'App\\Controller\\WishController:wish' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
