<?php

namespace ContainerXTjQmX9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_67PgdOaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.67PgdOa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.67PgdOa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'wish' => ['privates', '.errored..service_locator.67PgdOa.App\\Entity\\Wish', NULL, 'Cannot autowire service ".service_locator.67PgdOa": it references class "App\\Entity\\Wish" but no such service exists.'],
        ], [
            'em' => '?',
            'wish' => 'App\\Entity\\Wish',
        ]);
    }
}
