<?php

namespace ContainerNt58X6R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OAtEJ5BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OAtEJ5B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OAtEJ5B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\WishRepository', 'getWishRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.OAtEJ5B.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.OAtEJ5B": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\WishRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
