<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNt58X6R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNt58X6R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNt58X6R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNt58X6R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNt58X6R\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nt58X6R',
    'container.build_id' => 'ccaa3a08',
    'container.build_time' => 1630673902,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNt58X6R');
